// SPDX-FileCopyrightText: Copyright 2023 Citra Emulator Project
// SPDX-FileCopyrightText: Copyright 2024-2026 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include "common/types.h"

namespace Common::Log {

enum class Level : u8 {
    Trace,
    Debug,
    Info,
    Warning,
    Error,
    Critical,

    Count
};

enum class Class : u8 {
    Log,
    Common,
    Common_Filesystem,
    Common_Memory,
    Core,
    Core_Linker,
    Core_Devices,
    Config,
    Debug,
    Kernel,
    Kernel_Pthread,
    Kernel_Fs,
    Kernel_Vmm,
    Kernel_Event,
    Kernel_Sce,
    Lib,
    Lib_LibC,
    Lib_LibcInternal,
    Lib_Kernel,
    Lib_Pad,
    Lib_SystemGesture,
    Lib_GnmDriver,
    Lib_SystemService,
    Lib_UserService,
    Lib_VideoOut,
    Lib_CommonDlg,
    Lib_MsgDlg,
    Lib_AudioOut,
    Lib_AudioIn,
    Lib_Move,
    Lib_Net,
    Lib_NetCtl,
    Lib_SaveData,
    Lib_SaveDataDialog,
    Lib_Ssl,
    Lib_Ssl2,
    Lib_Http,
    Lib_Http2,
    Lib_SysModule,
    Lib_NpCommon,
    Lib_NpCommerce,
    Lib_NpAuth,
    Lib_NpManager,
    Lib_NpMatching2,
    Lib_NpScore,
    Lib_NpTrophy,
    Lib_NpTus,
    Lib_NpWebApi,
    Lib_NpWebApi2,
    Lib_NpProfileDialog,
    Lib_NpSnsFacebookDialog,
    Lib_Screenshot,
    Lib_LibCInternal,
    Lib_AppContent,
    Lib_Rtc,
    Lib_Rudp,
    Lib_DiscMap,
    Lib_Png,
    Lib_Jpeg,
    Lib_PlayGo,
    Lib_PlayGoDialog,
    Lib_Random,
    Lib_Usbd,
    Lib_Ajm,
    Lib_ErrorDialog,
    Lib_ImeDialog,
    Lib_AvPlayer,
    Lib_Ngs2,
    Lib_Audio3d,
    Lib_Ime,
    Lib_GameLiveStreaming,
    Lib_Remoteplay,
    Lib_SharePlay,
    Lib_Fiber,
    Lib_Vdec2,
    Lib_Videodec,
    Lib_Voice,
    Lib_RazorCpu,
    Lib_Mouse,
    Lib_WebBrowserDialog,
    Lib_NpParty,
    Lib_NpPartner,
    Lib_Zlib,
    Lib_Hmd,
    Lib_HmdSetupDialog,
    Lib_SigninDialog,
    Lib_Camera,
    Lib_CompanionHttpd,
    Lib_CompanionUtil,
    Lib_VrTracker,
    Lib_Font,
    Lib_FontFt,
    Frontend,
    Render,
    Render_Vulkan,
    Render_Recompiler,
    ImGui,
    Loader,
    Input,
    Tty,
    KeyManager,
    Count,
};

}
